### ISSUE TITLE
Not working properly on Chrome 90.x+ but working good in Chrome 89.x or less.

### ISSUE THREAD

**Issue by vstyler96** [rubenvar/csv-reader#10]
I can't share the screenshot now, but the table goes at the bottom instead of the top

**Comment by rubenvar** [comment]
Hey @vstyler96 thanks for reporting, I can't reproduce the issue though: I'm using the extension in Chrome 90.0 and it seems to work fine.

If you could share more details or a screenshot whenever you are able it would help. What is your OS? Do you think the result could be affected by another extension?

**Comment by vstyler96** [comment]
Settings:
![image](https://user-images.githubusercontent.com/46312870/115121963-152d0d80-9f7b-11eb-8f35-d4f00b242979.png)

Result:
![image](https://user-images.githubusercontent.com/46312870/115122123-e19eb300-9f7b-11eb-84c8-80ed69169331.png)

**Comment by rubenvar** [comment]
Is this still happening? I have not been able to reproduce it at all...
