### ISSUE TITLE
[Feature request] Keep last settings

### ISSUE THREAD

**Issue by Clorr** [rubenvar/csv-reader#13]
I bet this is a feature that is a lot waited for. It is also a feature that can be implemented in different ways because, it can be saved globally, for each page, or even autodetected.

From my side, I would suggest at least to just keep the last settings, if possible on the current page, because it is annoying to have to reset the same settings at every reload.

Anyway you did a very good job already, this would be just an improvment !!! Thanks for it !

**Comment by rubenvar** [comment]
Thanks for the suggestion @Clorr, I wated to add something like this isnce the beginning, but haven't used the extension for some time.

I was thinking about saving the last settings per page, maybe using localStorage. Will try to look into it.

**Comment by rubenvar** [comment]
This feature has been implemented in version 1.1.1: the extension now remembers the settings per url. Every time you come back to a url the previous settings are loaded into the extension popup.

Please try it and see if it fits your needs.
