### ISSUE TITLE
Try to download every page

### ISSUE THREAD

**Issue by sanflores** [rubenvar/csv-reader#15]
After accepting the new permissions, chrome is trying to download every tab/page I open, like hitting Ctrl+S

**Comment by sanflores** [comment]
Never mind, I've checked that this is fixed in 1.1.1, we'll need chrome to rollout the new version in the store

**Comment by rubenvar** [comment]
Thanks for writing @sanflores, that's right, after publishing the version with the bug I tried to immediately fix it (v1.1.1) but now the Chrome Web Store revision team is taking a long time to publish it... My appologies 🙏

**Comment by rubenvar** [comment]
Version 1.1.1 has been published, hopefully the bug is solved and we can enjoy the new features (remember user settings, stop `.csv` file downloads).
