### ISSUE TITLE
Background and text white

### ISSUE THREAD

**Issue by kaekae124** [rubenvar/csv-reader#17]
I only recently started using this extension (fantastic tool!), but according to people I've spoken to this issue is a recent bug. The text is all white and the background is also a very light color making the table almost impossible to read. I have my computer (a mac) set to dark mode but others I know don't have their computer on dark mode and still have this issue. 

Example using the provided example link: [this csv sample dataset](https://rubenvara.s3-eu-west-1.amazonaws.com/csv/dataNov-2-2020.csv)
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/29006519/184934316-90c9fcb8-a1fb-4f23-9779-d59cd5ed30bf.png">

**Comment by rubenvar** [comment]
Thanks for the report @kaekae124, I have just sent version 1.1.2 for revision in both Chrome and Firefox and this bug should be fixed when they approve and publish the new version.

**Comment by rubenvar** [comment]
Version 1.1.2 has finally been published to both Chrome and Firefox and I don't see the issue anymore.
