### ISSUE TITLE
addon not working

### ISSUE THREAD

**Issue by parsyy** [rubenvar/csv-reader#6]
add-on not working on Firefox 79.0

**Comment by rubenvar** [comment]
Hey @parsyy that's unfortunate, thanks for reporting!

I'm going to test it with Firefox 79.0 in these next few days and will try to find the issue (and hopefully fix it 🤞).

In the meantime, if you could let me know more about the problem you are having (how is it not working? maybe add a screenshot? is it not detecting a `.csv` page? or not parsing the CSV correctly?), it would be really helpful. Thanks!
